### ISSUE TITLE
unable to load from SD to DDR

### ISSUE THREAD

**Issue by bg2d** [lowRISC/lowrisc-quickstart#1]
Hello,

I followed the steps from [this](https://www.lowrisc.org/docs/getting-started/) document in order to start linux on lowrisc using Nexys4DDR board. The JP1 and JP2 are set properly and the SW1 in on. I configured the FPGA in two ways: QSPI and JTAG. In both configurations I get the following output in terminal after board is turned on:

[00]èalling main with MAC = eee1:e2e3e4e0
0: 0
1: 1
2: 1
3: 1
800: 1e
801: 0
802: 0
803: 0
Selftest iteration 1, next buffer = 0, rx_start = 4000
Selftest matches=2/2, delay = 9
Selftest iteration 2, next buffer = 1, rx_start = 4800
Selftest matches=4/4, delay = 9
Selftest iteration 3, next buffer = 2, rx_start = 5000
Selftest matches=8/8, delay = 9
Selftest iteration 4, next buffer = 3, rx_start = 5800
Selftest matches=16/16, delay = 16
Selftest iteration 5, next buffer = 4, rx_start = 6000
Selftest matches=32/32, delay = 31
Selftest iteration 6, next buffer = 5, rx_start = 6800
Selftest matches=64/64, delay = 60
Selftest iteration 7, next buffer = 6, rx_start = 7000
Selftest matches=128/128, delay = 119
Selftest iteration 8, next buffer = 7, rx_start = 7800
Selftest matches=187/187, delay = 173
lowRISC boot program

Hello LowRISC! Tue Aug 14 10:40:47 2018: Booting from FLASH because SW1 is high ..

u-boot based first stage boot loader
MMC:   
mmc created at 86800248, host = 86800200
lowrisc_sd: 0
Device: lowrisc_sd
Manufacturer ID: 27
OEM: 5048
Name: SD16G 
Bus Speed: 5000000
High Capacity: Yes
Capacity: 
lu.ld GiB
Bus Width: 4-bit

0:  fa b8 00 10 8e d0 bc 00 b0 b8 00 00 8e d8 8e c0 fb be 00 7c bf 00 06 b9 00 02 f3 a4 ea 21 06 00
20:  00 be be 07 38 04 75 0b 83 c6 10 81 fe fe 07 75 f3 eb 16 b4 02 b0 01 bb 00 7c b2 80 8a 74 01 8b
40:  4c 02 cd 13 ea 00 7c 00 00 eb fe 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
60:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
80:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
a0:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
c0:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
e0:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
100:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
120:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
140:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
160:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
180:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1a0:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ef be ad de 00 00 80 00
1c0:  01 01 0c 3f 1f 20 00 08 00 00 ff ff 00 00 00 00 01 21 83 3f 20 20 00 08 01 00 00 00 40 00 00 00
1e0:  01 21 82 3f a0 20 00 08 41 00 00 00 10 00 00 00 81 21 83 3f 60 d3 00 08 51 00 00 98 7d 01 55 aa
Load boot.bin into memory|Loaded 0 bytes to memory address 87000000 from boot.bin of 0 bytes.
hash = d41d8cd98f00b204e9800998ecf8427e
load elf to DDR memory
elf read failed with code 1Boot the loaded program...
mepc=80000002
mcause=instr illegal
mbadaddr=77773333
x0=0 ra =4000fc28 sp =4000d080 gp =1 
x4=87000000 x5=1b x6=4000 x7=1880 
x8=1000 x9=80000000 a0=40009550 a1=0 
a2=0 a3=0 a4=9 a5=40009380 
a6=80 a7=0 s2=0 s3=0 
s4=0 s5=0 s6=0 s7=0 
s8=87000000 s9=400002ca s10=d98c1dd4 s11=4000c74e 
x28=4000 x29=1b x30=4003c000 x31=1f 
error! exit(0x0000000000000539)
tohost_exit was called, and this version does not return

So the system is unable to load the boot.bin end the elf application from SD card into DDR memory. I checked the hash of boot.bin and it is correct.

**Comment by bg2d** [comment]
The issue was caused by the fact that the boot.bin file was generated incorrectly. Apparently, after I run `make getrelease` the boot.bin size was 0MB, the file was empty. I don't know what caused this but after I regenerated the files everything works fine.

**Comment by jrrk** [comment]
I suppose make getrelease is not as robust to errors as it could be.
